# Generated by Django 3.2.6 on 2021-08-12 13:57

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('apiTodo', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='todo',
            name='finish_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
